package assignment.model;
// Generated Aug 1, 2013 7:28:41 PM by Hibernate Tools 3.2.1.GA



/**
 * AssgEvaluateMst generated by hbm2java
 */
public class AssgEvaluateMst  implements java.io.Serializable {


     private Integer assgEvalId;
     private Integer assgSubmitId;
     private Integer assgMstId;
     private Integer assgUserId;
     private Integer assgEvaluatedMarks;
     private Integer assgTotalMarks;
     private Integer assgRejected;
     private Integer assgCopied;
     private String assgRemarks;
     private Integer assgEvalIdHide;

    public AssgEvaluateMst() {
    }

    public AssgEvaluateMst(Integer assgSubmitId, Integer assgMstId, Integer assgUserId, Integer assgEvaluatedMarks, Integer assgTotalMarks, Integer assgRejected, Integer assgCopied, String assgRemarks, Integer assgEvalIdHide) {
       this.assgSubmitId = assgSubmitId;
       this.assgMstId = assgMstId;
       this.assgUserId = assgUserId;
       this.assgEvaluatedMarks = assgEvaluatedMarks;
       this.assgTotalMarks = assgTotalMarks;
       this.assgRejected = assgRejected;
       this.assgCopied = assgCopied;
       this.assgRemarks = assgRemarks;
       this.assgEvalIdHide = assgEvalIdHide;
    }
   
    public Integer getAssgEvalId() {
        return this.assgEvalId;
    }
    
    public void setAssgEvalId(Integer assgEvalId) {
        this.assgEvalId = assgEvalId;
    }
    public Integer getAssgSubmitId() {
        return this.assgSubmitId;
    }
    
    public void setAssgSubmitId(Integer assgSubmitId) {
        this.assgSubmitId = assgSubmitId;
    }
    public Integer getAssgMstId() {
        return this.assgMstId;
    }
    
    public void setAssgMstId(Integer assgMstId) {
        this.assgMstId = assgMstId;
    }
    public Integer getAssgUserId() {
        return this.assgUserId;
    }
    
    public void setAssgUserId(Integer assgUserId) {
        this.assgUserId = assgUserId;
    }
    public Integer getAssgEvaluatedMarks() {
        return this.assgEvaluatedMarks;
    }
    
    public void setAssgEvaluatedMarks(Integer assgEvaluatedMarks) {
        this.assgEvaluatedMarks = assgEvaluatedMarks;
    }
    public Integer getAssgTotalMarks() {
        return this.assgTotalMarks;
    }
    
    public void setAssgTotalMarks(Integer assgTotalMarks) {
        this.assgTotalMarks = assgTotalMarks;
    }
    public Integer getAssgRejected() {
        return this.assgRejected;
    }
    
    public void setAssgRejected(Integer assgRejected) {
        this.assgRejected = assgRejected;
    }
    public Integer getAssgCopied() {
        return this.assgCopied;
    }
    
    public void setAssgCopied(Integer assgCopied) {
        this.assgCopied = assgCopied;
    }
    public String getAssgRemarks() {
        return this.assgRemarks;
    }
    
    public void setAssgRemarks(String assgRemarks) {
        this.assgRemarks = assgRemarks;
    }
    public Integer getAssgEvalIdHide() {
        return this.assgEvalIdHide;
    }
    
    public void setAssgEvalIdHide(Integer assgEvalIdHide) {
        this.assgEvalIdHide = assgEvalIdHide;
    }




}


