package assignment.model;
// Generated Aug 1, 2013 7:28:41 PM by Hibernate Tools 3.2.1.GA



/**
 * AssgGroupUser generated by hbm2java
 */
public class AssgGroupUser  implements java.io.Serializable {


     private Integer assgUsergroupId;
     private int assgGroupId;
     private int assgUserId;
     private String assgUserName;
     private Integer assgUsergroupIdHide;

    public AssgGroupUser() {
    }

	
    public AssgGroupUser(int assgGroupId, int assgUserId) {
        this.assgGroupId = assgGroupId;
        this.assgUserId = assgUserId;
    }
    public AssgGroupUser(int assgGroupId, int assgUserId, String assgUserName, Integer assgUsergroupIdHide) {
       this.assgGroupId = assgGroupId;
       this.assgUserId = assgUserId;
       this.assgUserName = assgUserName;
       this.assgUsergroupIdHide = assgUsergroupIdHide;
    }
   
    public Integer getAssgUsergroupId() {
        return this.assgUsergroupId;
    }
    
    public void setAssgUsergroupId(Integer assgUsergroupId) {
        this.assgUsergroupId = assgUsergroupId;
    }
    public int getAssgGroupId() {
        return this.assgGroupId;
    }
    
    public void setAssgGroupId(int assgGroupId) {
        this.assgGroupId = assgGroupId;
    }
    public int getAssgUserId() {
        return this.assgUserId;
    }
    
    public void setAssgUserId(int assgUserId) {
        this.assgUserId = assgUserId;
    }
    public String getAssgUserName() {
        return this.assgUserName;
    }
    
    public void setAssgUserName(String assgUserName) {
        this.assgUserName = assgUserName;
    }
    public Integer getAssgUsergroupIdHide() {
        return this.assgUsergroupIdHide;
    }
    
    public void setAssgUsergroupIdHide(Integer assgUsergroupIdHide) {
        this.assgUsergroupIdHide = assgUsergroupIdHide;
    }




}


