package assignment.model;
// Generated Aug 1, 2013 7:28:41 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AssgMst generated by hbm2java
 */
public class AssgMst  implements java.io.Serializable {


     private Integer assgId;
     private Integer assgOwnerId;
     private String assgTitle;
     private String assgSubject;
     private String assgDetails;
     private Integer assgDiscussionId;
     private Integer assgSubmitType;
     private Date assgSubmitDate;
     private String assgSubmissionDetails;
     private String assgFileUrl;
     private Integer assgIdHide;
     private Integer assgEvaluateIdHide;

    public AssgMst() {
    }

    public AssgMst(Integer assgOwnerId, String assgTitle, String assgSubject, String assgDetails, Integer assgDiscussionId, Integer assgSubmitType, Date assgSubmitDate, String assgSubmissionDetails, String assgFileUrl, Integer assgIdHide, Integer assgEvaluateIdHide) {
       this.assgOwnerId = assgOwnerId;
       this.assgTitle = assgTitle;
       this.assgSubject = assgSubject;
       this.assgDetails = assgDetails;
       this.assgDiscussionId = assgDiscussionId;
       this.assgSubmitType = assgSubmitType;
       this.assgSubmitDate = assgSubmitDate;
       this.assgSubmissionDetails = assgSubmissionDetails;
       this.assgFileUrl = assgFileUrl;
       this.assgIdHide = assgIdHide;
       this.assgEvaluateIdHide = assgEvaluateIdHide;
    }
   
    public Integer getAssgId() {
        return this.assgId;
    }
    
    public void setAssgId(Integer assgId) {
        this.assgId = assgId;
    }
    public Integer getAssgOwnerId() {
        return this.assgOwnerId;
    }
    
    public void setAssgOwnerId(Integer assgOwnerId) {
        this.assgOwnerId = assgOwnerId;
    }
    public String getAssgTitle() {
        return this.assgTitle;
    }
    
    public void setAssgTitle(String assgTitle) {
        this.assgTitle = assgTitle;
    }
    public String getAssgSubject() {
        return this.assgSubject;
    }
    
    public void setAssgSubject(String assgSubject) {
        this.assgSubject = assgSubject;
    }
    public String getAssgDetails() {
        return this.assgDetails;
    }
    
    public void setAssgDetails(String assgDetails) {
        this.assgDetails = assgDetails;
    }
    public Integer getAssgDiscussionId() {
        return this.assgDiscussionId;
    }
    
    public void setAssgDiscussionId(Integer assgDiscussionId) {
        this.assgDiscussionId = assgDiscussionId;
    }
    public Integer getAssgSubmitType() {
        return this.assgSubmitType;
    }
    
    public void setAssgSubmitType(Integer assgSubmitType) {
        this.assgSubmitType = assgSubmitType;
    }
    public Date getAssgSubmitDate() {
        return this.assgSubmitDate;
    }
    
    public void setAssgSubmitDate(Date assgSubmitDate) {
        this.assgSubmitDate = assgSubmitDate;
    }
    public String getAssgSubmissionDetails() {
        return this.assgSubmissionDetails;
    }
    
    public void setAssgSubmissionDetails(String assgSubmissionDetails) {
        this.assgSubmissionDetails = assgSubmissionDetails;
    }
    public String getAssgFileUrl() {
        return this.assgFileUrl;
    }
    
    public void setAssgFileUrl(String assgFileUrl) {
        this.assgFileUrl = assgFileUrl;
    }
    public Integer getAssgIdHide() {
        return this.assgIdHide;
    }
    
    public void setAssgIdHide(Integer assgIdHide) {
        this.assgIdHide = assgIdHide;
    }
    public Integer getAssgEvaluateIdHide() {
        return this.assgEvaluateIdHide;
    }
    
    public void setAssgEvaluateIdHide(Integer assgEvaluateIdHide) {
        this.assgEvaluateIdHide = assgEvaluateIdHide;
    }




}


