package assignment.model;
// Generated Aug 1, 2013 7:28:41 PM by Hibernate Tools 3.2.1.GA



/**
 * AssgGroupMst generated by hbm2java
 */
public class AssgGroupMst  implements java.io.Serializable {


     private Integer assgGroupId;
     private Integer assgGroupDtlId;
     private String assgGroupName;
     private String assgGroupDesc;
     private Integer assgGroupOwnerId;
     private Integer assgGroupIdHide;

    public AssgGroupMst() {
    }

    public AssgGroupMst(Integer assgGroupDtlId, String assgGroupName, String assgGroupDesc, Integer assgGroupOwnerId, Integer assgGroupIdHide) {
       this.assgGroupDtlId = assgGroupDtlId;
       this.assgGroupName = assgGroupName;
       this.assgGroupDesc = assgGroupDesc;
       this.assgGroupOwnerId = assgGroupOwnerId;
       this.assgGroupIdHide = assgGroupIdHide;
    }
   
    public Integer getAssgGroupId() {
        return this.assgGroupId;
    }
    
    public void setAssgGroupId(Integer assgGroupId) {
        this.assgGroupId = assgGroupId;
    }
    public Integer getAssgGroupDtlId() {
        return this.assgGroupDtlId;
    }
    
    public void setAssgGroupDtlId(Integer assgGroupDtlId) {
        this.assgGroupDtlId = assgGroupDtlId;
    }
    public String getAssgGroupName() {
        return this.assgGroupName;
    }
    
    public void setAssgGroupName(String assgGroupName) {
        this.assgGroupName = assgGroupName;
    }
    public String getAssgGroupDesc() {
        return this.assgGroupDesc;
    }
    
    public void setAssgGroupDesc(String assgGroupDesc) {
        this.assgGroupDesc = assgGroupDesc;
    }
    public Integer getAssgGroupOwnerId() {
        return this.assgGroupOwnerId;
    }
    
    public void setAssgGroupOwnerId(Integer assgGroupOwnerId) {
        this.assgGroupOwnerId = assgGroupOwnerId;
    }
    public Integer getAssgGroupIdHide() {
        return this.assgGroupIdHide;
    }
    
    public void setAssgGroupIdHide(Integer assgGroupIdHide) {
        this.assgGroupIdHide = assgGroupIdHide;
    }




}


