package common.model;
// Generated Jan 6, 2005 12:32:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CmnRoleMst generated by hbm2java
 */
public class CmnRoleMst  implements java.io.Serializable {


     private Long roleId;
     private String roleName;
     private String roleDesc;
     private String activateFlag;
     private Long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public CmnRoleMst() {
    }

	
    public CmnRoleMst(String roleName, String roleDesc, String activateFlag) {
        this.roleName = roleName;
        this.roleDesc = roleDesc;
        this.activateFlag = activateFlag;
    }
    public CmnRoleMst(String roleName, String roleDesc, String activateFlag, Long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.roleName = roleName;
       this.roleDesc = roleDesc;
       this.activateFlag = activateFlag;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
    public Long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getRoleDesc() {
        return this.roleDesc;
    }
    
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }
    public String getActivateFlag() {
        return this.activateFlag;
    }
    
    public void setActivateFlag(String activateFlag) {
        this.activateFlag = activateFlag;
    }
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


