package common.model;
// Generated Jan 6, 2005 12:32:04 AM by Hibernate Tools 3.2.1.GA



/**
 * CmnUniversityMst generated by hbm2java
 */
public class CmnUniversityMst  implements java.io.Serializable {


     private Long unvId;
     private String unvName;

    public CmnUniversityMst() {
    }

    public CmnUniversityMst(String unvName) {
       this.unvName = unvName;
    }
   
    public Long getUnvId() {
        return this.unvId;
    }
    
    public void setUnvId(Long unvId) {
        this.unvId = unvId;
    }
    public String getUnvName() {
        return this.unvName;
    }
    
    public void setUnvName(String unvName) {
        this.unvName = unvName;
    }




}


