package common.model;
// Generated Jan 6, 2005 12:32:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CmnUserRoleRlt generated by hbm2java
 */
public class CmnUserRoleRlt  implements java.io.Serializable {


     private Long userRoleId;
     private long userId;
     private long roleId;
     private String activateFlag;
     private long universityId;
     private Long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public CmnUserRoleRlt() {
    }

	
    public CmnUserRoleRlt(long userId, long roleId, long universityId) {
        this.userId = userId;
        this.roleId = roleId;
        this.universityId = universityId;
    }
    public CmnUserRoleRlt(long userId, long roleId, String activateFlag, long universityId, Long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.userId = userId;
       this.roleId = roleId;
       this.activateFlag = activateFlag;
       this.universityId = universityId;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
    public Long getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(Long userRoleId) {
        this.userRoleId = userRoleId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(long roleId) {
        this.roleId = roleId;
    }
    public String getActivateFlag() {
        return this.activateFlag;
    }
    
    public void setActivateFlag(String activateFlag) {
        this.activateFlag = activateFlag;
    }
    public long getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(long universityId) {
        this.universityId = universityId;
    }
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


