package common.model;
// Generated Jan 6, 2005 12:32:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CmnUserMst generated by hbm2java
 */
public class CmnUserMst  implements java.io.Serializable {


     private Long userId;
     private String userName;
     private String userPassword;
     private String isLocked;
     private String activateFlag;
     private String userFirstName;
     private String userMiddleName;
     private String userLastName;
     private Date userDateOfBirth;
     private Date firstLoginDate;
     private Date pwdChangedDate;
     private Long secretQueCode;
     private String secretAnswer;
     private Integer invalidLoginCnt;
     private Date unlockTime;
     private Long universityId;
     private String userActivationCode;
     private Long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public CmnUserMst() {
    }

	
    public CmnUserMst(String userName, String userPassword, String isLocked, String activateFlag, Long universityId) {
        this.userName = userName;
        this.userPassword = userPassword;
        this.isLocked = isLocked;
        this.activateFlag = activateFlag;
        this.universityId = universityId;
    }
    public CmnUserMst(String userName, String userPassword, String isLocked, String activateFlag, String userFirstName, String userMiddleName, String userLastName, Date userDateOfBirth, Date firstLoginDate, Date pwdChangedDate, Long secretQueCode, String secretAnswer, Integer invalidLoginCnt, Date unlockTime, Long universityId, String userActivationCode, Long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.userName = userName;
       this.userPassword = userPassword;
       this.isLocked = isLocked;
       this.activateFlag = activateFlag;
       this.userFirstName = userFirstName;
       this.userMiddleName = userMiddleName;
       this.userLastName = userLastName;
       this.userDateOfBirth = userDateOfBirth;
       this.firstLoginDate = firstLoginDate;
       this.pwdChangedDate = pwdChangedDate;
       this.secretQueCode = secretQueCode;
       this.secretAnswer = secretAnswer;
       this.invalidLoginCnt = invalidLoginCnt;
       this.unlockTime = unlockTime;
       this.universityId = universityId;
       this.userActivationCode = userActivationCode;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getIsLocked() {
        return this.isLocked;
    }
    
    public void setIsLocked(String isLocked) {
        this.isLocked = isLocked;
    }
    public String getActivateFlag() {
        return this.activateFlag;
    }
    
    public void setActivateFlag(String activateFlag) {
        this.activateFlag = activateFlag;
    }
    public String getUserFirstName() {
        return this.userFirstName;
    }
    
    public void setUserFirstName(String userFirstName) {
        this.userFirstName = userFirstName;
    }
    public String getUserMiddleName() {
        return this.userMiddleName;
    }
    
    public void setUserMiddleName(String userMiddleName) {
        this.userMiddleName = userMiddleName;
    }

    public String getUserLastName() {
        return userLastName;
    }

    public void setUserLastName(String userLastName) {
        this.userLastName = userLastName;
    }
    
    public Date getUserDateOfBirth() {
        return this.userDateOfBirth;
    }
    
    public void setUserDateOfBirth(Date userDateOfBirth) {
        this.userDateOfBirth = userDateOfBirth;
    }
    public Date getFirstLoginDate() {
        return this.firstLoginDate;
    }
    
    public void setFirstLoginDate(Date firstLoginDate) {
        this.firstLoginDate = firstLoginDate;
    }
    public Date getPwdChangedDate() {
        return this.pwdChangedDate;
    }
    
    public void setPwdChangedDate(Date pwdChangedDate) {
        this.pwdChangedDate = pwdChangedDate;
    }
    public Long getSecretQueCode() {
        return this.secretQueCode;
    }
    
    public void setSecretQueCode(Long secretQueCode) {
        this.secretQueCode = secretQueCode;
    }
    public String getSecretAnswer() {
        return this.secretAnswer;
    }
    
    public void setSecretAnswer(String secretAnswer) {
        this.secretAnswer = secretAnswer;
    }
    public Integer getInvalidLoginCnt() {
        return this.invalidLoginCnt;
    }
    
    public void setInvalidLoginCnt(Integer invalidLoginCnt) {
        this.invalidLoginCnt = invalidLoginCnt;
    }
    public Date getUnlockTime() {
        return this.unlockTime;
    }
    
    public void setUnlockTime(Date unlockTime) {
        this.unlockTime = unlockTime;
    }
    public Long getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }
    public String getUserActivationCode() {
        return this.userActivationCode;
    }
    
    public void setUserActivationCode(String userActivationCode) {
        this.userActivationCode = userActivationCode;
    }
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


