package GD.model;
// Generated Aug 1, 2013 7:28:41 PM by Hibernate Tools 3.2.1.GA



/**
 * ChatUser generated by hbm2java
 */
public class ChatUser  implements java.io.Serializable {


     private Integer chatUserId;
     private String chatUserName;
     private String chatUserDesc;
     private byte[] chatUserImage;
     private Integer chatUserVotes;

    public ChatUser() {
    }

    public ChatUser(String chatUserName, String chatUserDesc, byte[] chatUserImage, Integer chatUserVotes) {
       this.chatUserName = chatUserName;
       this.chatUserDesc = chatUserDesc;
       this.chatUserImage = chatUserImage;
       this.chatUserVotes = chatUserVotes;
    }
   
    public Integer getChatUserId() {
        return this.chatUserId;
    }
    
    public void setChatUserId(Integer chatUserId) {
        this.chatUserId = chatUserId;
    }
    public String getChatUserName() {
        return this.chatUserName;
    }
    
    public void setChatUserName(String chatUserName) {
        this.chatUserName = chatUserName;
    }
    public String getChatUserDesc() {
        return this.chatUserDesc;
    }
    
    public void setChatUserDesc(String chatUserDesc) {
        this.chatUserDesc = chatUserDesc;
    }
    public byte[] getChatUserImage() {
        return this.chatUserImage;
    }
    
    public void setChatUserImage(byte[] chatUserImage) {
        this.chatUserImage = chatUserImage;
    }
    public Integer getChatUserVotes() {
        return this.chatUserVotes;
    }
    
    public void setChatUserVotes(Integer chatUserVotes) {
        this.chatUserVotes = chatUserVotes;
    }




}


