package GD.model;
// Generated Aug 1, 2013 7:28:41 PM by Hibernate Tools 3.2.1.GA



/**
 * ChatPad generated by hbm2java
 */
public class ChatPad  implements java.io.Serializable {


     private Integer chatPadId;
     private String chatPadName;
     private String chatPadDesc;

    public ChatPad() {
    }

    public ChatPad(String chatPadName, String chatPadDesc) {
       this.chatPadName = chatPadName;
       this.chatPadDesc = chatPadDesc;
    }
   
    public Integer getChatPadId() {
        return this.chatPadId;
    }
    
    public void setChatPadId(Integer chatPadId) {
        this.chatPadId = chatPadId;
    }
    public String getChatPadName() {
        return this.chatPadName;
    }
    
    public void setChatPadName(String chatPadName) {
        this.chatPadName = chatPadName;
    }
    public String getChatPadDesc() {
        return this.chatPadDesc;
    }
    
    public void setChatPadDesc(String chatPadDesc) {
        this.chatPadDesc = chatPadDesc;
    }




}


