package GD.model;
// Generated Aug 1, 2013 7:28:41 PM by Hibernate Tools 3.2.1.GA



/**
 * ChatUserVote generated by hbm2java
 */
public class ChatUserVote  implements java.io.Serializable {


     private Integer chatVoteHisId;
     private Integer chatUserId;
     private Integer chatMsgId;
     private Integer chatVisible;

    public ChatUserVote() {
    }

    public ChatUserVote(Integer chatUserId, Integer chatMsgId, Integer chatVisible) {
       this.chatUserId = chatUserId;
       this.chatMsgId = chatMsgId;
       this.chatVisible = chatVisible;
    }
   
    public Integer getChatVoteHisId() {
        return this.chatVoteHisId;
    }
    
    public void setChatVoteHisId(Integer chatVoteHisId) {
        this.chatVoteHisId = chatVoteHisId;
    }
    public Integer getChatUserId() {
        return this.chatUserId;
    }
    
    public void setChatUserId(Integer chatUserId) {
        this.chatUserId = chatUserId;
    }
    public Integer getChatMsgId() {
        return this.chatMsgId;
    }
    
    public void setChatMsgId(Integer chatMsgId) {
        this.chatMsgId = chatMsgId;
    }
    public Integer getChatVisible() {
        return this.chatVisible;
    }
    
    public void setChatVisible(Integer chatVisible) {
        this.chatVisible = chatVisible;
    }




}


