package GD.model;
// Generated Aug 1, 2013 7:28:41 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ChatMsg generated by hbm2java
 */
public class ChatMsg  implements java.io.Serializable {


     private Integer chatMsgId;
     private Integer chatUserId;
     private Integer chatPadId;
     private Integer chatPositionId;
     private String chatMsgValue;
     private Date chatMsgTime;
     private Integer chatVisible;

    public ChatMsg() {
    }

    public ChatMsg(Integer chatUserId, Integer chatPadId, Integer chatPositionId, String chatMsgValue, Date chatMsgTime, Integer chatVisible) {
       this.chatUserId = chatUserId;
       this.chatPadId = chatPadId;
       this.chatPositionId = chatPositionId;
       this.chatMsgValue = chatMsgValue;
       this.chatMsgTime = chatMsgTime;
       this.chatVisible = chatVisible;
    }
   
    public Integer getChatMsgId() {
        return this.chatMsgId;
    }
    
    public void setChatMsgId(Integer chatMsgId) {
        this.chatMsgId = chatMsgId;
    }
    public Integer getChatUserId() {
        return this.chatUserId;
    }
    
    public void setChatUserId(Integer chatUserId) {
        this.chatUserId = chatUserId;
    }
    public Integer getChatPadId() {
        return this.chatPadId;
    }
    
    public void setChatPadId(Integer chatPadId) {
        this.chatPadId = chatPadId;
    }
    public Integer getChatPositionId() {
        return this.chatPositionId;
    }
    
    public void setChatPositionId(Integer chatPositionId) {
        this.chatPositionId = chatPositionId;
    }
    public String getChatMsgValue() {
        return this.chatMsgValue;
    }
    
    public void setChatMsgValue(String chatMsgValue) {
        this.chatMsgValue = chatMsgValue;
    }
    public Date getChatMsgTime() {
        return this.chatMsgTime;
    }
    
    public void setChatMsgTime(Date chatMsgTime) {
        this.chatMsgTime = chatMsgTime;
    }
    public Integer getChatVisible() {
        return this.chatVisible;
    }
    
    public void setChatVisible(Integer chatVisible) {
        this.chatVisible = chatVisible;
    }




}


