package quiz.model;
// Generated Aug 1, 2013 7:28:41 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * QzQuizes generated by hbm2java
 */
public class QzQuizes  implements java.io.Serializable {


     private Integer id;
     private int qzUserId;
     private String quizName;
     private String quizDesc;
     private String quizScope;
     private String quizSubject;
     private Date createdOn;
     private String createdBy;
     private String status;
     private String finalStatus;

    public QzQuizes() {
    }

	
    public QzQuizes(int qzUserId, Date createdOn, String createdBy, String status, String finalStatus) {
        this.qzUserId = qzUserId;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
        this.status = status;
        this.finalStatus = finalStatus;
    }
    public QzQuizes(int qzUserId, String quizName, String quizDesc, String quizScope, String quizSubject, Date createdOn, String createdBy, String status, String finalStatus) {
       this.qzUserId = qzUserId;
       this.quizName = quizName;
       this.quizDesc = quizDesc;
       this.quizScope = quizScope;
       this.quizSubject = quizSubject;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.status = status;
       this.finalStatus = finalStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getQzUserId() {
        return this.qzUserId;
    }
    
    public void setQzUserId(int qzUserId) {
        this.qzUserId = qzUserId;
    }
    public String getQuizName() {
        return this.quizName;
    }
    
    public void setQuizName(String quizName) {
        this.quizName = quizName;
    }
    public String getQuizDesc() {
        return this.quizDesc;
    }
    
    public void setQuizDesc(String quizDesc) {
        this.quizDesc = quizDesc;
    }
    public String getQuizScope() {
        return this.quizScope;
    }
    
    public void setQuizScope(String quizScope) {
        this.quizScope = quizScope;
    }
    public String getQuizSubject() {
        return this.quizSubject;
    }
    
    public void setQuizSubject(String quizSubject) {
        this.quizSubject = quizSubject;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getFinalStatus() {
        return this.finalStatus;
    }
    
    public void setFinalStatus(String finalStatus) {
        this.finalStatus = finalStatus;
    }




}


