package placeComm.model;
// Generated Sep 5, 2013 8:23:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HstAppointmentDtls generated by hbm2java
 */
public class HstAppointmentDtls  implements java.io.Serializable {


     private Long hstAppntDtlId;
     private long appntDtlId;
     private long userId;
     private String message;
     private String status;
     private long universityId;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public HstAppointmentDtls() {
    }

	
    public HstAppointmentDtls(long appntDtlId, long userId, long universityId, long createdUserId, Date createdDate) {
        this.appntDtlId = appntDtlId;
        this.userId = userId;
        this.universityId = universityId;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public HstAppointmentDtls(long appntDtlId, long userId, String message, String status, long universityId, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.appntDtlId = appntDtlId;
       this.userId = userId;
       this.message = message;
       this.status = status;
       this.universityId = universityId;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
    public Long getHstAppntDtlId() {
        return this.hstAppntDtlId;
    }
    
    public void setHstAppntDtlId(Long hstAppntDtlId) {
        this.hstAppntDtlId = hstAppntDtlId;
    }
    public long getAppntDtlId() {
        return this.appntDtlId;
    }
    
    public void setAppntDtlId(long appntDtlId) {
        this.appntDtlId = appntDtlId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public long getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(long universityId) {
        this.universityId = universityId;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


