package placeComm.model;
// Generated Aug 19, 2013 9:14:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PcAlumniDtls generated by hbm2java
 */
public class PcAlumniDtls  implements java.io.Serializable {


     private Long alumniDtlId;
     private String alumniName;
     private String alumniCompany;
     private String alumniDesignation;
     private String alumniBatch;
     private String alumniTelephone;
     private String alumniMobile;
     private String alumniEmail;
     private String alumniFax;
     private String alumniAddress;
     private String alumniOtherDtls;
     private String facebookLink;
     private String twitterLink;
     private String linkedinLink;
     private long universityId;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public PcAlumniDtls() {
    }

	
    public PcAlumniDtls(long createdUserId, Date createdDate) {
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public PcAlumniDtls(String alumniName, String alumniCompany, String alumniDesignation, String alumniBatch, String alumniTelephone, String alumniMobile, String alumniEmail, String alumniFax, String alumniAddress, String alumniOtherDtls, String facebookLink, String twitterLink, String linkedinLink,long universityId, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.alumniName = alumniName;
       this.alumniCompany = alumniCompany;
       this.alumniDesignation = alumniDesignation;
       this.alumniBatch = alumniBatch;
       this.alumniTelephone = alumniTelephone;
       this.alumniMobile = alumniMobile;
       this.alumniEmail = alumniEmail;
       this.alumniFax = alumniFax;
       this.alumniAddress = alumniAddress;
       this.alumniOtherDtls = alumniOtherDtls;
       this.facebookLink = facebookLink;
       this.twitterLink = twitterLink;
       this.linkedinLink = linkedinLink;
       this.universityId = universityId;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
    public Long getAlumniDtlId() {
        return this.alumniDtlId;
    }
    
    public void setAlumniDtlId(Long alumniDtlId) {
        this.alumniDtlId = alumniDtlId;
    }
    public String getAlumniName() {
        return this.alumniName;
    }
    
    public void setAlumniName(String alumniName) {
        this.alumniName = alumniName;
    }
    public String getAlumniCompany() {
        return this.alumniCompany;
    }
    
    public void setAlumniCompany(String alumniCompany) {
        this.alumniCompany = alumniCompany;
    }
    public String getAlumniDesignation() {
        return this.alumniDesignation;
    }
    
    public void setAlumniDesignation(String alumniDesignation) {
        this.alumniDesignation = alumniDesignation;
    }
    public String getAlumniBatch() {
        return this.alumniBatch;
    }
    
    public void setAlumniBatch(String alumniBatch) {
        this.alumniBatch = alumniBatch;
    }
    public String getAlumniTelephone() {
        return this.alumniTelephone;
    }
    
    public void setAlumniTelephone(String alumniTelephone) {
        this.alumniTelephone = alumniTelephone;
    }
    public String getAlumniMobile() {
        return this.alumniMobile;
    }
    
    public void setAlumniMobile(String alumniMobile) {
        this.alumniMobile = alumniMobile;
    }
    public String getAlumniEmail() {
        return this.alumniEmail;
    }
    
    public void setAlumniEmail(String alumniEmail) {
        this.alumniEmail = alumniEmail;
    }
    public String getAlumniFax() {
        return this.alumniFax;
    }
    
    public void setAlumniFax(String alumniFax) {
        this.alumniFax = alumniFax;
    }
    public String getAlumniAddress() {
        return this.alumniAddress;
    }
    
    public void setAlumniAddress(String alumniAddress) {
        this.alumniAddress = alumniAddress;
    }
    public String getAlumniOtherDtls() {
        return this.alumniOtherDtls;
    }
    
    public void setAlumniOtherDtls(String alumniOtherDtls) {
        this.alumniOtherDtls = alumniOtherDtls;
    }
    public String getFacebookLink() {
        return this.facebookLink;
    }
    
    public void setFacebookLink(String facebookLink) {
        this.facebookLink = facebookLink;
    }
    public String getTwitterLink() {
        return this.twitterLink;
    }
    
    public void setTwitterLink(String twitterLink) {
        this.twitterLink = twitterLink;
    }
    public String getLinkedinLink() {
        return this.linkedinLink;
    }
    
    public void setLinkedinLink(String linkedinLink) {
        this.linkedinLink = linkedinLink;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }

    public long getUniversityId() {
        return universityId;
    }

    public void setUniversityId(long universityId) {
        this.universityId = universityId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


