package placeComm.model;
// Generated Aug 25, 2013 10:09:54 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PcAppointmentDtls generated by hbm2java
 */
public class PcAppointmentDtls  implements java.io.Serializable {


     private Long appntDtlId;
     private String appntTitle;
     private String appntPurpose;
     private String appntFileName;
     private String appntCompany;
     private String assignedTo;
     private Long universityId;
     private String appntPriority;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;
     private Long ownerId;

    public PcAppointmentDtls() {
    }

	
    public PcAppointmentDtls(long createdUserId, Date createdDate) {
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public PcAppointmentDtls(String appntTitle, String appntPurpose, String appntFileName, String appntCompany, String assignedTo, Long universityId, String appntPriority, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate, Long ownerId) {
       this.appntTitle = appntTitle;
       this.appntPurpose = appntPurpose;
       this.appntFileName = appntFileName;
       this.appntCompany = appntCompany;
       this.assignedTo = assignedTo;
       this.universityId = universityId;
       this.appntPriority = appntPriority;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
       this.ownerId = ownerId;
    }
   
    public Long getAppntDtlId() {
        return this.appntDtlId;
    }
    
    public void setAppntDtlId(Long appntDtlId) {
        this.appntDtlId = appntDtlId;
    }
    public String getAppntTitle() {
        return this.appntTitle;
    }
    
    public void setAppntTitle(String appntTitle) {
        this.appntTitle = appntTitle;
    }
    public String getAppntPurpose() {
        return this.appntPurpose;
    }
    
    public void setAppntPurpose(String appntPurpose) {
        this.appntPurpose = appntPurpose;
    }
    public String getAppntFileName() {
        return this.appntFileName;
    }
    
    public void setAppntFileName(String appntFileName) {
        this.appntFileName = appntFileName;
    }
    public String getAppntCompany() {
        return this.appntCompany;
    }
    
    public void setAppntCompany(String appntCompany) {
        this.appntCompany = appntCompany;
    }
    public String getAssignedTo() {
        return this.assignedTo;
    }
    
    public void setAssignedTo(String assignedTo) {
        this.assignedTo = assignedTo;
    }

    public Long getUniversityId() {
        return universityId;
    }

    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }
   
    public String getAppntPriority() {
        return this.appntPriority;
    }
    
    public void setAppntPriority(String appntPriority) {
        this.appntPriority = appntPriority;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Long getOwnerId() {
        return this.ownerId;
    }
    
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }




}


