package placeComm.model;
// Generated Oct 2, 2013 4:47:52 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PcCompanyDtls generated by hbm2java
 */
public class PcCompanyDtls  implements java.io.Serializable {


     private Long companyId;
     private String companyTitle;
     private String companyCode;
     private String contactPersonName;
     private String contactNumber;
     private String contactAddress;
     private String contactEmail;
     private String companyLocation;
     private String companyPriority;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;
     private Long universityId;

    public PcCompanyDtls() {
    }

	
    public PcCompanyDtls(long createdUserId, Date createdDate) {
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public PcCompanyDtls(String companyTitle, String companyCode, String contactPersonName, String contactNumber, String contactAddress, String contactEmail, String companyLocation, String companyPriority, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate, Long universityId) {
       this.companyTitle = companyTitle;
       this.companyCode = companyCode;
       this.contactPersonName = contactPersonName;
       this.contactNumber = contactNumber;
       this.contactAddress = contactAddress;
       this.contactEmail = contactEmail;
       this.companyLocation = companyLocation;
       this.companyPriority = companyPriority;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
       this.universityId = universityId;
    }
   
    public Long getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
    public String getCompanyTitle() {
        return this.companyTitle;
    }
    
    public void setCompanyTitle(String companyTitle) {
        this.companyTitle = companyTitle;
    }
    public String getCompanyCode() {
        return this.companyCode;
    }
    
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }
    public String getContactPersonName() {
        return this.contactPersonName;
    }
    
    public void setContactPersonName(String contactPersonName) {
        this.contactPersonName = contactPersonName;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }
    public String getContactAddress() {
        return this.contactAddress;
    }
    
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }
    public String getCompanyLocation() {
        return this.companyLocation;
    }
    
    public void setCompanyLocation(String companyLocation) {
        this.companyLocation = companyLocation;
    }
    public String getCompanyPriority() {
        return this.companyPriority;
    }
    
    public void setCompanyPriority(String companyPriority) {
        this.companyPriority = companyPriority;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Long getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }




}


