package placeComm.model;
// Generated Nov 30, 2013 9:11:07 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PcHrDtls generated by hbm2java
 */
public class PcHrDtls  implements java.io.Serializable {


     private Long hrDtlId;
     private String hrName;
     private String companyId;
     private String designation;
     private String hrTeleNo;
     private String hrMobileNo;
     private String hrEmailId;
     private String faxId;
     private String address;
     private String otherDtls;
     private String facebookLink;
     private String twitterLink;
     private String linkedinLink;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;
     private Long universityId;
     private String activationCode;
     private Long hrUserId;
     private String companyTitle; //For display purpose only

    public PcHrDtls() {
    }

	
    public PcHrDtls(long createdUserId, Date createdDate) {
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public PcHrDtls(String hrName, String companyId, String designation, String hrTeleNo, String hrMobileNo, String hrEmailId, String faxId, String address, String otherDtls, String facebookLink, String twitterLink, String linkedinLink, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate, Long universityId, String activationCode, Long hrUserId,String companyTitle) {
       this.hrName = hrName;
       this.companyId = companyId;
       this.designation = designation;
       this.hrTeleNo = hrTeleNo;
       this.hrMobileNo = hrMobileNo;
       this.hrEmailId = hrEmailId;
       this.faxId = faxId;
       this.address = address;
       this.otherDtls = otherDtls;
       this.facebookLink = facebookLink;
       this.twitterLink = twitterLink;
       this.linkedinLink = linkedinLink;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
       this.universityId = universityId;
       this.activationCode = activationCode;
       this.hrUserId = hrUserId;
       this.companyTitle =companyTitle;
    }

    public PcHrDtls(Long hrDtlId, String hrName, String companyId, String designation, String hrTeleNo, String hrMobileNo, String hrEmailId, String faxId, String address, String otherDtls, String facebookLink, String twitterLink, String linkedinLink, Long universityId, String companyTitle) {
        this.hrDtlId = hrDtlId;
        this.hrName = hrName;
        this.companyId = companyId;
        this.designation = designation;
        this.hrTeleNo = hrTeleNo;
        this.hrMobileNo = hrMobileNo;
        this.hrEmailId = hrEmailId;
        this.faxId = faxId;
        this.address = address;
        this.otherDtls = otherDtls;
        this.facebookLink = facebookLink;
        this.twitterLink = twitterLink;
        this.linkedinLink = linkedinLink;
        this.universityId = universityId;
        this.companyTitle = companyTitle;
    }
   
    public Long getHrDtlId() {
        return this.hrDtlId;
    }
    
    public void setHrDtlId(Long hrDtlId) {
        this.hrDtlId = hrDtlId;
    }
    public String getHrName() {
        return this.hrName;
    }
    
    public void setHrName(String hrName) {
        this.hrName = hrName;
    }
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getHrTeleNo() {
        return this.hrTeleNo;
    }
    
    public void setHrTeleNo(String hrTeleNo) {
        this.hrTeleNo = hrTeleNo;
    }
    public String getHrMobileNo() {
        return this.hrMobileNo;
    }
    
    public void setHrMobileNo(String hrMobileNo) {
        this.hrMobileNo = hrMobileNo;
    }
    public String getHrEmailId() {
        return this.hrEmailId;
    }
    
    public void setHrEmailId(String hrEmailId) {
        this.hrEmailId = hrEmailId;
    }
    public String getFaxId() {
        return this.faxId;
    }
    
    public void setFaxId(String faxId) {
        this.faxId = faxId;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getOtherDtls() {
        return this.otherDtls;
    }
    
    public void setOtherDtls(String otherDtls) {
        this.otherDtls = otherDtls;
    }
    public String getFacebookLink() {
        return this.facebookLink;
    }
    
    public void setFacebookLink(String facebookLink) {
        this.facebookLink = facebookLink;
    }
    public String getTwitterLink() {
        return this.twitterLink;
    }
    
    public void setTwitterLink(String twitterLink) {
        this.twitterLink = twitterLink;
    }
    public String getLinkedinLink() {
        return this.linkedinLink;
    }
    
    public void setLinkedinLink(String linkedinLink) {
        this.linkedinLink = linkedinLink;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Long getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }
    public String getActivationCode() {
        return this.activationCode;
    }
    
    public void setActivationCode(String activationCode) {
        this.activationCode = activationCode;
    }
    public Long getHrUserId() {
        return this.hrUserId;
    }
    
    public void setHrUserId(Long hrUserId) {
        this.hrUserId = hrUserId;
    }

    public String getCompanyTitle() {
        return companyTitle;
    }

    public void setCompanyTitle(String companyTitle) {
        this.companyTitle = companyTitle;
    }

    


}


