package placeComm.model;
// Generated Oct 16, 2013 1:57:42 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PcInterestInvitesDtls generated by hbm2java
 */
public class PcInterestInvitesDtls  implements java.io.Serializable {


     private Long invtDtlId;
     private String companyId;
     private String jobDesc;
     private Date lastDate;
     private String jobDescDoc;
     private String otherDetails;
     private long universityId;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;
     private String companyTitle; //For display purpose only
     
    public PcInterestInvitesDtls() {
    }

	
    public PcInterestInvitesDtls(long universityId, long createdUserId, Date createdDate) {
        this.universityId = universityId;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public PcInterestInvitesDtls(String companyId, String jobDesc, Date lastDate, String jobDescDoc, String otherDetails, long universityId, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.companyId = companyId;
       this.jobDesc = jobDesc;
       this.lastDate = lastDate;
       this.jobDescDoc = jobDescDoc;
       this.otherDetails = otherDetails;
       this.universityId = universityId;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
    public PcInterestInvitesDtls(Long invtDtlId,String companyId,String companyTitle,String jobDesc,Date lastDate,String jobDescDoc,String otherDetails)
    {
       this.invtDtlId = invtDtlId ;
       this.companyId = companyId;
       this.companyTitle = companyTitle;
       this.jobDesc = jobDesc;
       this.lastDate = lastDate;
       this.jobDescDoc = jobDescDoc;
       this.otherDetails = otherDetails;
      
    }
    public Long getInvtDtlId() {
        return this.invtDtlId;
    }
    
    public void setInvtDtlId(Long invtDtlId) {
        this.invtDtlId = invtDtlId;
    }
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    public String getJobDesc() {
        return this.jobDesc;
    }

    public String getCompanyTitle() {
        return companyTitle;
    }

    public void setCompanyTitle(String companyTitle) {
        this.companyTitle = companyTitle;
    }
       
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc;
    }
    public Date getLastDate() {
        return this.lastDate;
    }
    
    public void setLastDate(Date lastDate) {
        this.lastDate = lastDate;
    }
    public String getJobDescDoc() {
        return this.jobDescDoc;
    }
    
    public void setJobDescDoc(String jobDescDoc) {
        this.jobDescDoc = jobDescDoc;
    }
    public String getOtherDetails() {
        return this.otherDetails;
    }
    
    public void setOtherDetails(String otherDetails) {
        this.otherDetails = otherDetails;
    }
    public long getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(long universityId) {
        this.universityId = universityId;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


