package user.model;
// Generated Jul 12, 2013 11:27:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserOrganizationDtls generated by hbm2java
 */
public class UserOrganizationDtls  implements java.io.Serializable {


     private Long orgDtlId;
     private String orgName;
     private String orgTitle;
     private Integer orgStartMonth;
     private Integer orgStartYear;
     private Integer orgEndMonth;
     private Integer orgEndYear;
     private String orgLocation;
     private String orgDescription;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public UserOrganizationDtls() {
    }

	
    public UserOrganizationDtls(String orgName, long createdUserId, Date createdDate) {
        this.orgName = orgName;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public UserOrganizationDtls(String orgName, String orgTitle, Integer orgStartMonth, Integer orgStartYear, Integer orgEndMonth, Integer orgEndYear, String orgLocation, String orgDescription, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.orgName = orgName;
       this.orgTitle = orgTitle;
       this.orgStartMonth = orgStartMonth;
       this.orgStartYear = orgStartYear;
       this.orgEndMonth = orgEndMonth;
       this.orgEndYear = orgEndYear;
       this.orgLocation = orgLocation;
       this.orgDescription = orgDescription;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
    public Long getOrgDtlId() {
        return this.orgDtlId;
    }
    
    public void setOrgDtlId(Long orgDtlId) {
        this.orgDtlId = orgDtlId;
    }
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
    public String getOrgTitle() {
        return this.orgTitle;
    }
    
    public void setOrgTitle(String orgTitle) {
        this.orgTitle = orgTitle;
    }
    public Integer getOrgStartMonth() {
        return this.orgStartMonth;
    }
    
    public void setOrgStartMonth(Integer orgStartMonth) {
        this.orgStartMonth = orgStartMonth;
    }
    public Integer getOrgStartYear() {
        return this.orgStartYear;
    }
    
    public void setOrgStartYear(Integer orgStartYear) {
        this.orgStartYear = orgStartYear;
    }
    public Integer getOrgEndMonth() {
        return this.orgEndMonth;
    }
    
    public void setOrgEndMonth(Integer orgEndMonth) {
        this.orgEndMonth = orgEndMonth;
    }
    public Integer getOrgEndYear() {
        return this.orgEndYear;
    }
    
    public void setOrgEndYear(Integer orgEndYear) {
        this.orgEndYear = orgEndYear;
    }
    public String getOrgLocation() {
        return this.orgLocation;
    }
    
    public void setOrgLocation(String orgLocation) {
        this.orgLocation = orgLocation;
    }
    public String getOrgDescription() {
        return this.orgDescription;
    }
    
    public void setOrgDescription(String orgDescription) {
        this.orgDescription = orgDescription;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


