package user.model;
// Generated Nov 8, 2013 11:52:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserPersonalDtls generated by hbm2java
 */
public class UserPersonalDtls  implements java.io.Serializable {


     private Long personalDtlId;
     private String personPhoto;
     private Date dateOfBirth;
     private String gender;
     private String primaryLangauge;
     private String secondaryLanguage;
     private String interests;
     private String currentCity;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;
     private Long universityId;
     private String facebookLink;
     private String twitterLink;
     private String linkedInLink;

     //For Display Purpose
     private Long userId;
     private String userFirstName;
     private String userMiddleName;
     private String userLastName;
     
    public UserPersonalDtls() {
    }

    public UserPersonalDtls(String gender, long createdUserId, Date createdDate) {
        this.gender = gender;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
	
    public UserPersonalDtls(Long userId,String userFirstName,String userMiddleName,String userLastName,String gender, String facebookLink, String twitterLink, String linkedInLink) {
        this.userId = userId;
        this.userFirstName = userFirstName;
        this.userMiddleName = userMiddleName;
        this.userLastName = userLastName;
        this.gender = gender;
        this.facebookLink = facebookLink;
        this.twitterLink = twitterLink;
        this.linkedInLink = linkedInLink;
    }
    public UserPersonalDtls(String personPhoto, Date dateOfBirth, String gender, String primaryLangauge, String secondaryLanguage, String interests, String currentCity, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate, Long universityId, String facebookLink, String twitterLink, String linkedInLink) {
       this.personPhoto = personPhoto;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.primaryLangauge = primaryLangauge;
       this.secondaryLanguage = secondaryLanguage;
       this.interests = interests;
       this.currentCity = currentCity;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
       this.universityId = universityId;
       this.facebookLink = facebookLink;
       this.twitterLink = twitterLink;
       this.linkedInLink = linkedInLink;
    }
   
    public Long getPersonalDtlId() {
        return this.personalDtlId;
    }
    
    public void setPersonalDtlId(Long personalDtlId) {
        this.personalDtlId = personalDtlId;
    }
    public String getPersonPhoto() {
        return this.personPhoto;
    }
    
    public void setPersonPhoto(String personPhoto) {
        this.personPhoto = personPhoto;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPrimaryLangauge() {
        return this.primaryLangauge;
    }
    
    public void setPrimaryLangauge(String primaryLangauge) {
        this.primaryLangauge = primaryLangauge;
    }
    public String getSecondaryLanguage() {
        return this.secondaryLanguage;
    }
    
    public void setSecondaryLanguage(String secondaryLanguage) {
        this.secondaryLanguage = secondaryLanguage;
    }
    public String getInterests() {
        return this.interests;
    }
    
    public void setInterests(String interests) {
        this.interests = interests;
    }
    public String getCurrentCity() {
        return this.currentCity;
    }
    
    public void setCurrentCity(String currentCity) {
        this.currentCity = currentCity;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Long getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }
    public String getFacebookLink() {
        return this.facebookLink;
    }
    
    public void setFacebookLink(String facebookLink) {
        this.facebookLink = facebookLink;
    }
    public String getTwitterLink() {
        return this.twitterLink;
    }
    
    public void setTwitterLink(String twitterLink) {
        this.twitterLink = twitterLink;
    }
    public String getLinkedInLink() {
        return this.linkedInLink;
    }
    
    public void setLinkedInLink(String linkedInLink) {
        this.linkedInLink = linkedInLink;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserFirstName() {
        return userFirstName;
    }

    public void setUserFirstName(String userFirstName) {
        this.userFirstName = userFirstName;
    }

    public String getUserMiddleName() {
        return userMiddleName;
    }

    public void setUserMiddleName(String userMiddleName) {
        this.userMiddleName = userMiddleName;
    }

    public String getUserLastName() {
        return userLastName;
    }

    public void setUserLastName(String userLastName) {
        this.userLastName = userLastName;
    }

}


