package admin.model;
// Generated Nov 30, 2013 9:10:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TmpUserExcelData generated by hbm2java
 */
public class TmpUserExcelData  implements java.io.Serializable {


     private Long id;
     private String rollNo;
     private String userFullName;
     private String emailId;
     private String userType;
     private String activationCode;
     private long universityId;
     private long createdUserId;
     private Date createdDate;
     private Long userId;

    public TmpUserExcelData() {
    }

	
    public TmpUserExcelData(String rollNo, String emailId, String userType, String activationCode, long universityId, long createdUserId, Date createdDate) {
        this.rollNo = rollNo;
        this.emailId = emailId;
        this.userType = userType;
        this.activationCode = activationCode;
        this.universityId = universityId;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public TmpUserExcelData(String rollNo, String userFullName, String emailId, String userType, String activationCode, long universityId, long createdUserId, Date createdDate, Long userId) {
       this.rollNo = rollNo;
       this.userFullName = userFullName;
       this.emailId = emailId;
       this.userType = userType;
       this.activationCode = activationCode;
       this.universityId = universityId;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.userId = userId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getRollNo() {
        return this.rollNo;
    }
    
    public void setRollNo(String rollNo) {
        this.rollNo = rollNo;
    }
    public String getUserFullName() {
        return this.userFullName;
    }
    
    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getActivationCode() {
        return this.activationCode;
    }
    
    public void setActivationCode(String activationCode) {
        this.activationCode = activationCode;
    }
    public long getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(long universityId) {
        this.universityId = universityId;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }




}


